In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [10]:
folder = "../assets/dataset/"
fn = "1.txt"
path = os.path.join(folder, fn)

df  = pd.read_csv(path, header = None, delimiter = r"\s+")

In [12]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,66,67,68,69,70,71,72,73,74,75
0,0.103402,0.012627,0.463011,-0.488976,0.818425,-0.301876,-0.859680,-0.510748,0.007622,-0.147343,...,0.141228,-0.264752,0.953918,0.000075,0.000302,0.000117,-0.000011,-0.000011,0.000005,-0.874277
1,0.103369,0.012636,0.463027,-0.489053,0.818396,-0.301829,-0.859644,-0.510807,0.007673,-0.147295,...,0.141228,-0.264752,0.953918,0.000075,0.000302,0.000117,-0.000011,-0.000011,0.000005,-0.874277
2,0.103338,0.012652,0.463046,-0.488982,0.818438,-0.301828,-0.859687,-0.510735,0.007663,-0.147281,...,0.141228,-0.264752,0.953918,0.000075,0.000302,0.000117,-0.000011,-0.000011,0.000005,-0.874277
3,0.103321,0.012656,0.463049,-0.489023,0.818421,-0.301807,-0.859665,-0.510771,0.007678,-0.147269,...,0.141228,-0.264752,0.953918,0.000075,0.000302,0.000117,-0.000011,-0.000011,0.000005,-0.874277
4,0.103299,0.012650,0.463037,-0.488960,0.818453,-0.301823,-0.859695,-0.510722,0.007625,-0.147306,...,0.141228,-0.264752,0.953918,0.000075,0.000302,0.000117,-0.000011,-0.000011,0.000005,-0.874277

In [17]:
ix = 1
df.iloc[0, ix - 1]

0.103402

In [19]:
ixi = 1
ixf = 4
df.iloc[0, ixi - 1: ixf]

0    0.103402
1    0.012627
2    0.463011
3   -0.488976
Name: 0, dtype: float64